name: Sync Markdown to Confluence

on:
  push:
    paths:
      - 'docs/*.md'
  workflow_dispatch:  

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with write access
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Push changed markdown pages to Confluence
        env:
          CONFLUENCE_API_URL: ${{ secrets.CONFLUENCE_API_URL }}
          CONFLUENCE_USER: ${{ secrets.CONFLUENCE_USER }}
          CONFLUENCE_TOKEN: ${{ secrets.CONFLUENCE_TOKEN }}
        run: |
          changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^docs/.*\.md' || true)
          for file in $changed; do
            echo "🔼 Updating $file"
            python confluence_sync/push_to_confluence.py "$file"
          done

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push README or PDF link updates
        run: |
          git add README.md
          git diff --cached --quiet || git commit -m "🔄 Auto-sync from Confluence"
          git push
